### ISSUE TITLE
TypeError: stat: path should be string,

### ISSUE THREAD

**Issue by lminer** [mkutarna/audiobook_gen#8]
This is a great project! I'm getting this error right now. Any idea what might be the issue?

![image](https://user-images.githubusercontent.com/5126549/206579371-97274ffa-aecd-4fa3-bddf-3d7162cf83ba.png)

**Comment by mkutarna** [comment]
Thanks for trying it out and opening this issue. Could you please describe the steps you took to arrive there, and the uploaded file? Are you running it locally or the HuggingFace Space demo?

**Comment by lminer** [comment]
I tried both locally and via the huggingface demo and got the identical error. It might be an issue with the ebook. I can send it on to you if you give me an email address.

**Comment by lminer** [comment]
just sent it

**Comment by mkutarna** [comment]
Based on testing - it looks like this error is caused by a mismatch between how `streamlit` handles file uploads and how `ebooklib` handles reading epub files. `st.file_uploader` creates a file-like object, but `read_epub` expects a file path. I'm exploring workarounds based on temporary files.

**Comment by mkutarna** [comment]
Based on local testing - this workaround allows the epub files to generate audio. Next step is to push to HFS to test online.

**Comment by mkutarna** [comment]
@lminer 

I have changed how the epub files are handled on upload - and was able to run your file through on the HuggingFace Space demo (great topic). Please give it a try again and let me know if there are any further issues.

**Comment by lminer** [comment]
It runs, but there appears to be an issue with streamlit file management on osx. Perhaps because `/media` doesn't exist?

```
2022-12-17 10:27:00.612 Uncaught exception GET /media/f234a8fec762cf8fd0cf31173c73b71e4a2daa58dddfad72eabf834f.zip?title=app%20%C2%B7%20Streamlit (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8501', method='GET', uri='/media/f234a8fec762cf8fd0cf31173c73b71e4a2daa58dddfad72eabf834f.zip?title=app%20%C2%B7%20Streamlit', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File ".../mambaforge/envs/audiobook_gen/lib/python3.9/site-packages/streamlit/runtime/memory_media_file_storage.py", line 140, in get_file
    return self._files_by_id[file_id]
KeyError: 'f234a8fec762cf8fd0cf31173c73b71e4a2daa58dddfad72eabf834f'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".../mambaforge/envs/audiobook_gen/lib/python3.9/site-packages/tornado/web.py", line 1713, in _execute
    result = await result
  File ".../mambaforge/envs/audiobook_gen/lib/python3.9/site-packages/tornado/web.py", line 2616, in get
    self.set_headers()
  File ".../mambaforge/envs/audiobook_gen/lib/python3.9/site-packages/tornado/web.py", line 2727, in set_headers
    self.set_extra_headers(self.path)
  File ".../mambaforge/envs/audiobook_gen/lib/python3.9/site-packages/streamlit/web/server/media_file_handler.py", line 59, in set_extra_headers
    media_file = self._storage.get_file(path)
  File ".../mambaforge/envs/audiobook_gen/lib/python3.9/site-packages/streamlit/runtime/memory_media_file_storage.py", line 142, in get_file
    raise MediaFileStorageError(
streamlit.runtime.media_file_storage.MediaFileStorageError: Bad filename 'f234a8fec762cf8fd0cf31173c73b71e4a2daa58dddfad72eabf834f.zip'. (No media file with id 'f234a8fec762cf8fd0cf31173c73b71e4a2daa58dddfad72eabf834f')
2022-12-17 10:27:00.614 500 GET /media/f234a8fec762cf8fd0cf31173c73b71e4a2daa58dddfad72eabf834f.zip?title=app%20%C2%B7%20Streamlit (127.0.0.1) 154.94ms
```
